#!/bin/dash

if [ "$#" -eq 0 ]; then
	if [ -d ".legit" ]; then
		echo "legit-init: error: .legit already exists"
	else
		mkdir ".legit"
		mkdir ".legit/index"
		mkdir ".legit/repository"
		mkdir ".legit/branch"
		mkdir ".legit/branch/master"
		mkdir ".legit/commit_msg"
		mkdir ".legit/curr_branch"
		mkdir ".legit/curr_branch/master"
		echo "Initialized empty legit repository in .legit"
	fi
else
	echo "usage: legit-init"
fi
